spring:
  application:
    name: iam

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:master}
  admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
