server:
  port: 8000

spring:
  application:
    name: audit
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: audit-service
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
